### ISSUE TITLE
Integrating react application with the angular microfrontends

### ISSUE THREAD

**Issue by sanjanaadeshra** [joeldenning/coexisting-angular-microfrontends#1]
I am trying to integrate a react applications by making it a part of the imports in the index.html file for the root-html-field as:
{ "imports": { "app1": "http://localhost:4201/main.js",
"login": "http://localhost:4204/main.js",
"react-example": "http://localhost:4206/index.js",
"app2": "http://localhost:4202/main.js",
"navbar": "http://localhost:4203/main.js",
 "single-spa": "https://unpkg.com/single-spa@4.3.2/lib/system/single-spa.min.js" } }

But it is giving me the following error:
Access to script at 'http://localhost:4206/index.js' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
system.min.js:4 GET http://localhost:4206/index.js net::ERR_FAILED

Is there anything you can suggest to resolve this?

**Comment by joeldenning** [comment]
Yeah, that looks you could fix that by modifying your webpack-dev-server config. If you're using create-react-app, I believe (but am not totally sure) that that requires you to eject your config so you can modify it.

```js
// webpack.config.js
module.exports = {
  devServer: {
    headers: {
      'Access-Control-Allow-Origin': '*',
    }
  }
}
```

Also, be sure to [correctly set](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/app1/src/set-public-path.ts) your [public path](https://webpack.js.org/configuration/output/#outputpublicpath).

Closing this for now, but feel free to reopen if that doesn't work.
