### ISSUE TITLE
Safari 9+ support

### ISSUE THREAD

**Issue by ATLSAPI** [joeldenning/coexisting-angular-microfrontends#11]
When running in Safari 9.1 on macOS, the page doesn't load. See the errors attached. I've tried adding a polyfill for Promise (bluebird) and [Fetch API ](https://github.com/github/fetch) according to the systemjs readme but that doesn't work either.

![single-spa-angular-safari-9 1](https://user-images.githubusercontent.com/9756583/61543839-2494c500-aa3c-11e9-954b-924f5009c6e3.PNG)

**Comment by ATLSAPI** [comment]
**UPDATE** This issue will likely happen on any browser without support for ES6/ES2015 and above. 

**SOLUTION** After transpiling system.min.js, amd.min.js and namedexports.js dependencies to ES5  manually using babel, the application loaded and I could navigate to the spas with few console errors (Also tested on IE10 and Safari 8 it still works). I haven't done extensive testing as this is a simple app. 
I intend to set up a build to automate the transpilation of all the dependencies of the root HTML app for the project I'm working on.

NB: I didn't need to transpile namedregister.js but you may need if you encounter this issue on other browsers.

@joeldenning what you like me to do with this issue in terms of a resolution. Is it worth adding something to single-spa docs if it's not in there already? and the readme of this repo too? Please let me know.

**Comment by joeldenning** [comment]
For coexisting angular microfrontends, I'd rather not update it to support Safari 9. I'm surprised that you ran into systemjs not working in Safari 9. If that's the case, please open an issue on systemjs itself. I am also a maintainer of systemjs, but Guy Bedford is the primary maintainer. We can take a look to see if systemjs supports safari 9.
