### ISSUE TITLE
Upgrade an example with Angular 13.

### ISSUE THREAD

**Issue by hamzazaidi** [joeldenning/coexisting-angular-microfrontends#120]
I am trying for days but no success using `create-single-spa` cli to create angular project but getting error

https://single-spa.slack.com/files/U02RQ5JF05P/F02RJGM0DPF/screen_shot_2021-12-21_at_9.22.52_pm.png

Using a CLI should be a seamless experience like React.
Thanks

**Comment by internettrans** [comment]
The proper place to ask questions and report bugs is Slack or https://github.com/single-spa/single-spa-angular
