### ISSUE TITLE
Use IDE Debugger

### ISSUE THREAD

**Issue by gawielgo** [joeldenning/coexisting-angular-microfrontends#124]
Hi everyone!!!
you know if it would be possible to connect a JavaScript Debug (from the ide) to the root and after that set breakpoint in the other app for debug simultaneously the whole system?

I've been trying for a couple of days but without getting any positive results...

**Comment by internettrans** [comment]
I don't maintain this project very much anymore. The github.com/angular-microfrontends repo is the one we're trying to switch over to. This question might be better asked in single-spa Slack or single-spa-angular github
