### ISSUE TITLE
Error on domElementGetter on Browser Back Button.

### ISSUE THREAD

**Issue by baggelisp** [joeldenning/coexisting-angular-microfrontends#15]
Hello,
My page has 2 layouts in master app, one with full width and one with sidebar and main section.
I want to place my angular app inside the main section of my page.
On back button i have this message:

![Screenshot from 2019-09-29 17-11-39](https://user-images.githubusercontent.com/40744856/65833806-e25dee80-e2dc-11e9-8a2d-70b4b171b8ec.png)

The domElementGetter returning null because the document.body is not ready yet.

Here is my code on main.sinlge-spa.ts

```
var el;
function domElementGetter() {
  el = document.getElementById('main-section');
  console.log("inside dome element")
  if (!el) {
    console.log("el doent not exist")
    return existingElement();
  }
  else{
    el = document.getElementById('main-section');
    return el;
  }
}
function existingElement(){
  var checkExist = setInterval(function() { 
    console.log("test") 
    console.log(document.body) 
    if (document.getElementById('main-section')) { 
      console.log("Element Exists!"); 
      clearInterval(checkExist); 
      return document.getElementById('main-section');
    } }, 100);
}
```

Any ideas?

**Comment by joeldenning** [comment]
> The domElementGetter returning null because the document.body is not ready yet.

Your code must be pretty different than the coexisting-angular-microfrontends code, since [we call singleSpa.start() inside of document.body](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/root-html-file/index.html#L31).

You should not need to worry about any of this. single-spa-angular creates a dom element container for you without you having to create it in the html file or your own custom domElementGetter.

To fix your code, just put your javascript into the `<body>` element of the HTML.

I'm closing this since this does not seem like an issue with coexisting-angular-microfrontends and I've given you a way to fix it.

**Comment by baggelisp** [comment]
The code is exacly the sameas the coexisting-angular-microfrontends code but in the navbar app i want to have a sidebar instead of navbar.So my code in the navbar html is like this:

```
<div class="container-fluid">
    <div class="row">
        <div class="col-3">
            <div style="text-align:center">
                <h1>
                    Sidebar
                </h1>
                <div class="list-group list-group-flush">
                    <a routerLink="/home" href="#">Home</a>
                    <a routerLink="/login" href="#">Log in</a>
                </div>
            </div>
        </div>
        <div class="col-9">
            <div id="main-section">
            </div>
        </div>
    </div>
</div>
```
And i want to place my home-page-app inside div with id "main-section"

So in the home-page app in the main.single-spa.ts i put the function:

```
function domElementGetter() {
  let el = document.getElementById('main-section');
  if (!el) {
    el = document.createElement('div');
    el.id = 'main-section';
    document.body.appendChild(el);
  }
  return el;
}
```

All working well and i have this result:

![1](https://user-images.githubusercontent.com/40744856/65840133-c4fd4480-e31d-11e9-8bf5-35f43fcac84e.png)


But when back button is pressed the document.getElementById('main-section') returns undefined and this happened:

![2](https://user-images.githubusercontent.com/40744856/65840145-e6f6c700-e31d-11e9-9102-483f5d57bbd8.png)

That is the reason why i changed the code in the main.single-spa.ts in the home-page app to the code i posted to find the element first and after return the DOM element.
But as i saw in the console with the comments the main.single-spa.ts is running before the DOM is generated and that is why return undefined.

**Comment by joeldenning** [comment]
For back button related issues, see https://github.com/CanopyTax/single-spa-angular/issues/94.

Your error makes no sense for it to be related to the back button. Please push your code to github and we can reopen this for me to look at. The `setInterval` stuff you have is incorrect and shouldn't be needed.
