### ISSUE TITLE
Lazy-loading fails when microfrontend port is hosted on different port

### ISSUE THREAD

**Issue by harish-valuelabs** [joeldenning/coexisting-angular-microfrontends#16]
Lets say I'm hosting shell app on port 5500. And my app main bundle is available on port 4200. When a module  is lazy loaded (for app on port 4200), network request goes on Port 5500 instead of port 4200. Hence it fails as 404. Any suggestions on how to handle it ?

**Comment by joeldenning** [comment]
Yep, this is something missing from coexisting-angular-microfrontends. The solution is [dynamic webpack public path](https://webpack.js.org/guides/public-path/#on-the-fly). The easiest way is to use [systemjs-webpack-interop](https://github.com/joeldenning/systemjs-webpack-interop) to set the public path.

Would you be interested in creating a PR that adds systemjs-webpack-interop to each of the applications in this coexisting-angular-microfrontends repo?

**Comment by harish-valuelabs** [comment]
Sure, I'll give it a try.
