### ISSUE TITLE
Application not unmounting

### ISSUE THREAD

**Issue by brechtvhb** [joeldenning/coexisting-angular-microfrontends#18]
Currently we have a situation similar to the example in this repository.

We  have a root application. Navigation and 2 other applications (template-builder and pdf-printer).
Everything seems to work fine but we have one issue. When click a URL in the navigation (to switch between applications). The new application gets loaded but the other one remains on the screen.

We're quite clueless about it as we can't find any major diffirencese between our application and this example. The only diffirence we can see is that our sub-applications are a bit more complex having multiple routes. 

```
const routes: Routes = [
   {
      path: 'pdf-templates',
      component: PdfTemplateListComponent,
      data: { title: 'List of PDF template' },
   },
   {
      path: 'pdf-templates/:id',
      component: PdfTemplateDetailComponent,
      data: { title: 'PDF template detail' },
   },
   { path: '', redirectTo: '/pdf-templates', pathMatch: 'full' },
   { path: '**', component: EmptyRouteComponent }
];

@NgModule({
   imports: [RouterModule.forRoot(routes)],
   exports: [RouterModule],
   providers: [{ provide: APP_BASE_HREF, useValue: '/' }]
})
export class AppRoutingModule { }
```

The CSS of the child application does seem to get unloaded tough, but the HTML remains on the page.

Can you give us any pointers that could help us?

**Comment by brechtvhb** [comment]
Using the single spa inspector plugin (https://chrome.google.com/webstore/detail/single-spa-inspector/emldbibkihanfiaiaghebffnbahjcgcp) I see the applications do get into the unmounted state. 
When I onmount my navigation app the HTML gets removed. When I unmount the other 2 the HTML remains on the page.

**Comment by brechtvhb** [comment]
Turns out the issue was because we were using the BrowserAnimationsModule.

**Comment by joeldenning** [comment]
Glad to hear you figured out what is causing it. See related https://github.com/CanopyTax/single-spa-angular/issues/60
