### ISSUE TITLE
"Accessing Shared State in a Non-Single-SPA Micro-Frontend Application"

### ISSUE THREAD

**Issue by Simran-Mudaliar** [joeldenning/coexisting-angular-microfrontends#183]
I'm building an application using a micro-frontend architecture. Here are the different micro-apps I have:

- **SpaApp1**: An Angular application for core services.
- **SpaApp2**: An Angular application for the login page.
- **@org/SharedApp**: A shared application responsible for maintaining the state (e.g., auth token, user info) across all micro-apps.
- **@org/root-config**: The root application that imports and connects all other micro-apps.

In addition to these, I have **App3**, a NestJS application (not currently integrated with single-spa) that makes backend API calls. **SpaApp1** uses GraphQL to query responses from **App3**.

I want to use the shared state from **@org/SharedApp** (which contains the auth token and user information) within **App3**. Currently, it seems like I would need to integrate **App3** with the single-spa library to achieve this. Is there an alternative approach that would allow **App3** to access the shared state from **@org/SharedApp** without integrating with single-spa?

**Comment by internettrans** [comment]
NestJS is a server-side framework, single-spa is usually (but not always) client rendered. Are you wanting to share the in-browser client data with the NestJS server? If so, serialization would be needed.

Integrating NestJS with single-spa would likely be very difficult. I tried with NextJS but the code I had to modify in node_modules was so messy that I didn't even want to release it. My guess (without experience in NestJS) is that it assumes total control over the HTML file, which is not a good starting point for a single-spa integration.
