### ISSUE TITLE
How to pass custom prop while registering application in html file

### ISSUE THREAD

**Issue by Harry-027** [joeldenning/coexisting-angular-microfrontends#19]
For example, let's say I created my own class for a bus event in a separate file which imports various methods from other libraries as well. How can I pass instance of that class as a customprop to registerApplication method, since it's in html file under System.import , I'm facing error : cannot use import statement outside a module

**Comment by joeldenning** [comment]
Great question. A couple options:

1. Move the registerApplication calls into their own in-browser javascript module that is bundled and is in the import map. Then change your html file to System.import() that module.
2. System.import() a module before calling registerApplication:

```html
<script>
  System.import('some-module').then(m => {
    const customProps = {eventBus: m.eventBus}
    singleSpa.registerApplication('app1', () => System.import('app1'), () => true, customProps)
    singleSpa.start()
  })
</script>
```
