### ISSUE TITLE
Reload page in one app don't work  - 404 NOT FOUND

### ISSUE THREAD

**Issue by juedizor** [joeldenning/coexisting-angular-microfrontends#2]
Currently I clone project and deploy that, when I am in the path app1 or app2 and reload browser it doesn't work, show message 404 The requested path could not be found. 

Do you have any idea for this error ?

**Comment by luisdlino** [comment]
Same here, any updates?

**Comment by joeldenning** [comment]
This is a bug in an npm package that I'm using that only happens when using on Windows. See related https://github.com/CanopyTax/single-spa-angular/issues/70. The code that isn't working is [the `serve` npm package](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/root-html-file/package.json#L6).

Pull requests accepted to fix this -- I won't get around to this for about a week. What we need is a static server that will always return the index.html file instead of an HTTP 404 when a frontend route is requested.

**Comment by juedizor** [comment]
OK, if I configured a server always in any route redirect to index.html, the reload works ? Now, Other problem that I have is when I have diferent apps with diferents css, a lot of times one css change other style  of my app

**Comment by joeldenning** [comment]
> OK, if I configured a server always in any route redirect to index.html, the reload works ?

Yes, exactly. That's what [serve -s](https://github.com/joeldenning/coexisting-angular-microfrontends/blob/master/root-html-file/package.json#L6) does in all OS except windows. If you find an npm package that does this well on windows and isn't gigantic or awful, I'd appreciate a PR for it, too.

> Now, Other problem that I have is when I have diferent apps with diferents css, a lot of times one css change other style of my app

You need to name your css classes in a way that is unique to the application. You could just prefix your css classes, eg `.app1-card`, if you would like to. Or you could use something like [BEM](https://en.bem.info/methodology/quick-start/) as a naming convention for your classes.

**Comment by juedizor** [comment]
Ok, I have that: 

app1: Use bootstrap with class .app1-card
app2: Use bootstrap with class .app2-card

when I import app1 and app2 the css works fine, because all apps are building within a div with each css, but when I have bootstrap in the main app this css modify the behavior in app1 or app2. 

Do you have any idea ?

**Comment by luisdlino** [comment]
Joel or juedizor, is systemjs using lazy loading? like with angular core just loading first time?

**Comment by joeldenning** [comment]
@luisdlino yes SystemJS does lazy loading. It won’t download any of the apps until you navigate to a route that they are active for. See https://single-spa.js.org/docs/configuration.html#loading-function-or-application for how this integrates with single-spa, and see https://github.com/systemjs/systemjs for more info on systemjs

**Comment by joeldenning** [comment]
Closing because original issue is fixed as described in the linked issue
