### ISSUE TITLE
custom font awesome or styles

### ISSUE THREAD

**Issue by ponnalaxmikanth** [joeldenning/coexisting-angular-microfrontends#25]
How can we load custom font awesome files in spa application?

**Comment by joeldenning** [comment]
An easy way is to use font awesome via CDN, such as [the official font awesome cdn](https://fontawesome.com/start) or [bootstrap cdn](https://www.bootstrapcdn.com/fontawesome/).

You said you want to use custom font awesome files, which might indicate that a CDN won't work for you. In that case, check out [these docs](https://single-spa.js.org/docs/ecosystem-angular#angular-assets). Specifically, take a look at the Angular assets, Scripts, and Styles sections.
