### ISSUE TITLE
urls from environment.ts

### ISSUE THREAD

**Issue by ponnalaxmikanth** [joeldenning/coexisting-angular-microfrontends#26]
how can i register application from environment.ts files using angular 8? this way i will avoid hard coding urls in index.html file and derive them from environment files based on environment.

**Comment by joeldenning** [comment]
In general, I prefer just registering all the applications in every environment, and using in-browser environment and permission checks to hide/show things in the UI.

However, if you would like to deviate from that suggestion, here's one way to do it.

html file:
```ejs
<script type="systemjs-importmap" src="<%= urlSpecificToEnvironment %>"></script>
<script>
System.import('environment-vars').then(module => {
  module.singleSpaApplications.forEach(a => {
    singleSpa.registerApplication(a.name, () => System.import(a.name), routePrefix(a.prefix))
  })
})
</script>
```

import map:
```json
{
  "imports": {
    "environment-vars": "https://some-env.domain.com/environment-vars/version-number/environment-vars.js"
  }
}
```

environment-vars.js
```js
export const singleSpaApplications = [
  {
    name: 'thing',
    prefix: 'thing'
  }
]
```
