### ISSUE TITLE
How event communication between sub-applications

### ISSUE THREAD

**Issue by SmallProgramIndustry** [joeldenning/coexisting-angular-microfrontends#38]
Hello! 
  E.g：
    app1 Have login
![image](https://user-images.githubusercontent.com/33216614/77617053-266d3b80-6f6e-11ea-9cf0-09fde5710c84.png)

   1.   app2 How to call app1 login？

   2.   How to declare global variables  (How to declare global variables for multiple items )? 

   3.   Can you give a simple example in the project？

   Reading the source code is clearer and more intuitive than the documentation, thank you！

**Comment by joeldenning** [comment]
> app2 How to call app1 login？

Applications can communicate with each other by importing each other. See https://single-spa.js.org/docs/recommended-setup#inter-app-communication

> How to declare global variables (How to declare global variables for multiple items )?

`window.thing = 'value'`

> Can you give a simple example in the project？

There are a lot of examples at https://single-spa.js.org/docs/recommended-setup#inter-app-communication and https://single-spa.js.org/docs/examples
