### ISSUE TITLE
Can we have Proxy

### ISSUE THREAD

**Issue by ajaykumarsana** [joeldenning/coexisting-angular-microfrontends#56]
Hi @joeldenning  @Vallerious @varora1406 

I wanted to have some api calls in [app1](http://coexisting-angular-microfrontends.surge.sh/app1) so can i have proxy configuration in [root-html-file](https://github.com/joeldenning/coexisting-angular-microfrontends/tree/master/root-html-file) or some other place.

Please help.
Thanks,
Ajay

**Comment by varora1406** [comment]
If you want to do some changes and check it, go ahead with cloning the project and make any suitable changes locally as you want.
If you want to submit this change in this repository here, then I would like to ask the purpose of adding those calls, what benefit does it add here 🙂

**Comment by ajaykumarsana** [comment]
Hi @varora1406 ,

Actually i tried having proxy in [root-html-file](https://github.com/joeldenning/coexisting-angular-microfrontends/tree/master/root-html-file) but npm **serve**  package doesn't give provision to use or i dont know how to use.
Can you please help?

**Comment by varora1406** [comment]
Please provide a repository link with your problem.
it will help me in helping you

**Comment by joeldenning** [comment]
You can replace `serve` with any static server that can proxy. https://www.npmjs.com/search?q=proxy%20static

**Comment by ajaykumarsana** [comment]
I've used webpack in root-html and then configured proxy in devserver.
