### ISSUE TITLE
App.component not rendered 

### ISSUE THREAD

**Issue by tezine** [joeldenning/coexisting-angular-microfrontends#57]
Hi, 
After `npm i` and `npm start`, App.component is not rendered in the browser. There's an empty page with an empty app1-root element on it. It seems the bootstrap process is not working as expected. App.component constructor is not even executed. 
Any ideas?

**Comment by tezine** [comment]
Sorry, my bad. 
I just changed the suggested url when replacing App1 from //localhost:4201/app1.js to http://localhost:4201/main.js and now it works perfectly!

**Comment by joeldenning** [comment]
Closing this since it has been resolved.
