### ISSUE TITLE
IE Support

### ISSUE THREAD

**Issue by dnelso18** [joeldenning/coexisting-angular-microfrontends#9]
Does not support IE/Edge
Symbol is undefined
Promise is undefined
Syntax Error

**Comment by joeldenning** [comment]
Approach for fixing this is to add some polyfills into root-html-file. See https://angular.io/guide/browser-support#polyfills-for-non-cli-users. We likely just need the core-js/client/shim.min.js file, which we can just script tag to point to cdnjs. See https://cdnjs.com/libraries/core-js

**Comment by ATLSAPI** [comment]
I tried it and it does work on Edge 42.17134.1.0. What version have you got @dnelso18? Perhaps it doesn't work on older Edge versions? 

@joeldenning I'll give that a go and let you know how it goes

**Comment by dnelso18** [comment]
Sorry, should have specified. Currently on:
       IE v11.0.9600.19377
      Edge 42.17134

@ATLSAPI what results did you get when trying the polyfill?

**Comment by joeldenning** [comment]
This was fixed in https://github.com/joeldenning/coexisting-angular-microfrontends/pull/10 via @crorodriguezro.

See related documentation https://single-spa.js.org/docs/ecosystem-angular.html#internet-explorer
